### ISSUE TITLE
validate packet/equinix metal functionality

### ISSUE THREAD

**Issue by rsmitty** [talos-systems/cluster-api-bootstrap-provider-talos#128]
A community member was having issues when using our bootstrap provider (v0.3.2) with the packet CAPI provider. the generated metadata didn't have `#!talos` at the top. We should validate if this is a reproducible bug.

**Comment by smira** [comment]
I wonder if Packet provider got changed? https://github.com/talos-systems/cluster-api-bootstrap-provider-talos/blob/8e39bd731f06f14e642d7ffad202aec44948a492/controllers/talosconfig_controller.go#L322-L342

**Comment by smira** [comment]
I wonder though if the code has a bug around line 339: should it be `InfrastructureRef.Kind`, not `.Name`, @rsmitty ?
